# Generated by Django 5.1 on 2024-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_doctor_patient_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
